version: '3.8'
services:
#  grpc_server:
#    image: 043309331568.dkr.ecr.us-east-1.amazonaws.com/development-data-gateway-grpc:91378d467f1ef056c4f40b2e3e445633cae362c3
#    ports:
#      - "50051:50051"
#    environment:
#      PORT: 50051


  app:
    image: protobuf:latest
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint:
      - /bin/sh
      - -c
      - |
        rm -rf pkg/pb
        mkdir -p pkg/pb
        protoc --go_out=pkg/pb --go_opt=paths=source_relative \
               --go-grpc_out=pkg/pb --go-grpc_opt=paths=source_relative \
               proto/*.proto
        chmod 777 -R pkg/pb