version: '3.8'
services:
  protoc-go:
    image: namely/protoc-all:latest
    volumes:
      - ./:/defs
    working_dir: /defs
    command: >
      -f proto/**/*.proto -l go -o pkg --go-source-relative
#    entrypoint:
#      - /bin/sh
#      - -c
#      - |
#        rm -rf pkg/*
#        protoc -I proto/ proto/**/.proto --go_out=pkg --go_opt=paths=source_relative
#  protoc-js:
#    image: namely/protoc-all:latest
#    volumes:
#      - ./:/defs
#    working_dir: /defs
#    command: >
#      -f proto/*.proto -l web -o generated/js
#


