version: '3.8'
services:
  app:
    image: protobuf:latest
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint:
      - /bin/sh
      - -c
      - |
        protoc -I=proto --go_out=pkg/pb --go_opt=paths=source_relative \
               --go-grpc_out=pkg/pb --go-grpc_opt=paths=source_relative \
               proto/*.proto
        chmod 777 -R pkg/pb

#  grpc_server:
#    image: grpc_server:latest
#    ports:
#      - "50051:50051"
#    environment:
#      PORT: 50051
