// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/document_type.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentTypeService_Save_FullMethodName = "/domain.DocumentTypeService/Save"
	DocumentTypeService_Find_FullMethodName = "/domain.DocumentTypeService/Find"
)

// DocumentTypeServiceClient is the client API for DocumentTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentTypeServiceClient interface {
	Save(ctx context.Context, in *DocumentTypeRequest, opts ...grpc.CallOption) (*DocumentTypeResponse, error)
	Find(ctx context.Context, in *DocumentTypeRequest, opts ...grpc.CallOption) (*DocumentTypeListResponse, error)
}

type documentTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentTypeServiceClient(cc grpc.ClientConnInterface) DocumentTypeServiceClient {
	return &documentTypeServiceClient{cc}
}

func (c *documentTypeServiceClient) Save(ctx context.Context, in *DocumentTypeRequest, opts ...grpc.CallOption) (*DocumentTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentTypeResponse)
	err := c.cc.Invoke(ctx, DocumentTypeService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentTypeServiceClient) Find(ctx context.Context, in *DocumentTypeRequest, opts ...grpc.CallOption) (*DocumentTypeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentTypeListResponse)
	err := c.cc.Invoke(ctx, DocumentTypeService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentTypeServiceServer is the server API for DocumentTypeService service.
// All implementations must embed UnimplementedDocumentTypeServiceServer
// for forward compatibility.
type DocumentTypeServiceServer interface {
	Save(context.Context, *DocumentTypeRequest) (*DocumentTypeResponse, error)
	Find(context.Context, *DocumentTypeRequest) (*DocumentTypeListResponse, error)
	mustEmbedUnimplementedDocumentTypeServiceServer()
}

// UnimplementedDocumentTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentTypeServiceServer struct{}

func (UnimplementedDocumentTypeServiceServer) Save(context.Context, *DocumentTypeRequest) (*DocumentTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedDocumentTypeServiceServer) Find(context.Context, *DocumentTypeRequest) (*DocumentTypeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedDocumentTypeServiceServer) mustEmbedUnimplementedDocumentTypeServiceServer() {}
func (UnimplementedDocumentTypeServiceServer) testEmbeddedByValue()                             {}

// UnsafeDocumentTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentTypeServiceServer will
// result in compilation errors.
type UnsafeDocumentTypeServiceServer interface {
	mustEmbedUnimplementedDocumentTypeServiceServer()
}

func RegisterDocumentTypeServiceServer(s grpc.ServiceRegistrar, srv DocumentTypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDocumentTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentTypeService_ServiceDesc, srv)
}

func _DocumentTypeService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentTypeServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentTypeService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentTypeServiceServer).Save(ctx, req.(*DocumentTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentTypeService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentTypeServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentTypeService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentTypeServiceServer).Find(ctx, req.(*DocumentTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentTypeService_ServiceDesc is the grpc.ServiceDesc for DocumentTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.DocumentTypeService",
	HandlerType: (*DocumentTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _DocumentTypeService_Save_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _DocumentTypeService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/document_type.proto",
}
