// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/document_type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *DocumentTypeRequest) Reset() {
	*x = DocumentTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentTypeRequest) ProtoMessage() {}

func (x *DocumentTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentTypeRequest.ProtoReflect.Descriptor instead.
func (*DocumentTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_type_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DocumentTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *DocumentTypeResponse) Reset() {
	*x = DocumentTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentTypeResponse) ProtoMessage() {}

func (x *DocumentTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentTypeResponse.ProtoReflect.Descriptor instead.
func (*DocumentTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_type_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentTypeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentTypeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DocumentTypeListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DocumentTypeResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DocumentTypeListResponse) Reset() {
	*x = DocumentTypeListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentTypeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentTypeListResponse) ProtoMessage() {}

func (x *DocumentTypeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentTypeListResponse.ProtoReflect.Descriptor instead.
func (*DocumentTypeListResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_type_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentTypeListResponse) GetList() []*DocumentTypeResponse {
	if x != nil {
		return x.List
	}
	return nil
}

var File_proto_document_type_proto protoreflect.FileDescriptor

var file_proto_document_type_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0x39, 0x0a, 0x13, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3a,
	0x0a, 0x14, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x18, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x9f, 0x01, 0x0a, 0x13, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x41, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64, 0x12, 0x1b, 0x2e, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_document_type_proto_rawDescOnce sync.Once
	file_proto_document_type_proto_rawDescData = file_proto_document_type_proto_rawDesc
)

func file_proto_document_type_proto_rawDescGZIP() []byte {
	file_proto_document_type_proto_rawDescOnce.Do(func() {
		file_proto_document_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_document_type_proto_rawDescData)
	})
	return file_proto_document_type_proto_rawDescData
}

var file_proto_document_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_document_type_proto_goTypes = []any{
	(*DocumentTypeRequest)(nil),      // 0: domain.DocumentTypeRequest
	(*DocumentTypeResponse)(nil),     // 1: domain.DocumentTypeResponse
	(*DocumentTypeListResponse)(nil), // 2: domain.DocumentTypeListResponse
}
var file_proto_document_type_proto_depIdxs = []int32{
	1, // 0: domain.DocumentTypeListResponse.list:type_name -> domain.DocumentTypeResponse
	0, // 1: domain.DocumentTypeService.Save:input_type -> domain.DocumentTypeRequest
	0, // 2: domain.DocumentTypeService.Find:input_type -> domain.DocumentTypeRequest
	1, // 3: domain.DocumentTypeService.Save:output_type -> domain.DocumentTypeResponse
	2, // 4: domain.DocumentTypeService.Find:output_type -> domain.DocumentTypeListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_document_type_proto_init() }
func file_proto_document_type_proto_init() {
	if File_proto_document_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_document_type_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DocumentTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_type_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DocumentTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_type_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DocumentTypeListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_document_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_document_type_proto_goTypes,
		DependencyIndexes: file_proto_document_type_proto_depIdxs,
		MessageInfos:      file_proto_document_type_proto_msgTypes,
	}.Build()
	File_proto_document_type_proto = out.File
	file_proto_document_type_proto_rawDesc = nil
	file_proto_document_type_proto_goTypes = nil
	file_proto_document_type_proto_depIdxs = nil
}
