// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: categories_services.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoriesServicesService_Create_FullMethodName  = "/domain.CategoriesServicesService/Create"
	CategoriesServicesService_Update_FullMethodName  = "/domain.CategoriesServicesService/Update"
	CategoriesServicesService_FindAll_FullMethodName = "/domain.CategoriesServicesService/FindAll"
	CategoriesServicesService_FindOne_FullMethodName = "/domain.CategoriesServicesService/FindOne"
	CategoriesServicesService_Enabled_FullMethodName = "/domain.CategoriesServicesService/Enabled"
	CategoriesServicesService_Disable_FullMethodName = "/domain.CategoriesServicesService/Disable"
)

// CategoriesServicesServiceClient is the client API for CategoriesServicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoriesServicesServiceClient interface {
	Create(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesResponse, error)
	Update(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesResponse, error)
	FindAll(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesListResponse, error)
	FindOne(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesResponse, error)
	Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*CategoriesServicesResponse, error)
	Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*CategoriesServicesResponse, error)
}

type categoriesServicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoriesServicesServiceClient(cc grpc.ClientConnInterface) CategoriesServicesServiceClient {
	return &categoriesServicesServiceClient{cc}
}

func (c *categoriesServicesServiceClient) Create(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesServicesResponse)
	err := c.cc.Invoke(ctx, CategoriesServicesService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesServicesServiceClient) Update(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesServicesResponse)
	err := c.cc.Invoke(ctx, CategoriesServicesService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesServicesServiceClient) FindAll(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesServicesListResponse)
	err := c.cc.Invoke(ctx, CategoriesServicesService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesServicesServiceClient) FindOne(ctx context.Context, in *CategoriesServicesRequest, opts ...grpc.CallOption) (*CategoriesServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesServicesResponse)
	err := c.cc.Invoke(ctx, CategoriesServicesService_FindOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesServicesServiceClient) Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*CategoriesServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesServicesResponse)
	err := c.cc.Invoke(ctx, CategoriesServicesService_Enabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesServicesServiceClient) Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*CategoriesServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoriesServicesResponse)
	err := c.cc.Invoke(ctx, CategoriesServicesService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoriesServicesServiceServer is the server API for CategoriesServicesService service.
// All implementations must embed UnimplementedCategoriesServicesServiceServer
// for forward compatibility.
type CategoriesServicesServiceServer interface {
	Create(context.Context, *CategoriesServicesRequest) (*CategoriesServicesResponse, error)
	Update(context.Context, *CategoriesServicesRequest) (*CategoriesServicesResponse, error)
	FindAll(context.Context, *CategoriesServicesRequest) (*CategoriesServicesListResponse, error)
	FindOne(context.Context, *CategoriesServicesRequest) (*CategoriesServicesResponse, error)
	Enabled(context.Context, *Entity) (*CategoriesServicesResponse, error)
	Disable(context.Context, *Entity) (*CategoriesServicesResponse, error)
	mustEmbedUnimplementedCategoriesServicesServiceServer()
}

// UnimplementedCategoriesServicesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoriesServicesServiceServer struct{}

func (UnimplementedCategoriesServicesServiceServer) Create(context.Context, *CategoriesServicesRequest) (*CategoriesServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCategoriesServicesServiceServer) Update(context.Context, *CategoriesServicesRequest) (*CategoriesServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCategoriesServicesServiceServer) FindAll(context.Context, *CategoriesServicesRequest) (*CategoriesServicesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedCategoriesServicesServiceServer) FindOne(context.Context, *CategoriesServicesRequest) (*CategoriesServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedCategoriesServicesServiceServer) Enabled(context.Context, *Entity) (*CategoriesServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enabled not implemented")
}
func (UnimplementedCategoriesServicesServiceServer) Disable(context.Context, *Entity) (*CategoriesServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedCategoriesServicesServiceServer) mustEmbedUnimplementedCategoriesServicesServiceServer() {
}
func (UnimplementedCategoriesServicesServiceServer) testEmbeddedByValue() {}

// UnsafeCategoriesServicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoriesServicesServiceServer will
// result in compilation errors.
type UnsafeCategoriesServicesServiceServer interface {
	mustEmbedUnimplementedCategoriesServicesServiceServer()
}

func RegisterCategoriesServicesServiceServer(s grpc.ServiceRegistrar, srv CategoriesServicesServiceServer) {
	// If the following call pancis, it indicates UnimplementedCategoriesServicesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoriesServicesService_ServiceDesc, srv)
}

func _CategoriesServicesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriesServicesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriesServicesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriesServicesServiceServer).Create(ctx, req.(*CategoriesServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriesServicesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriesServicesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriesServicesService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriesServicesServiceServer).Update(ctx, req.(*CategoriesServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriesServicesService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriesServicesServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriesServicesService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriesServicesServiceServer).FindAll(ctx, req.(*CategoriesServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriesServicesService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriesServicesServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriesServicesService_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriesServicesServiceServer).FindOne(ctx, req.(*CategoriesServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriesServicesService_Enabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriesServicesServiceServer).Enabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriesServicesService_Enabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriesServicesServiceServer).Enabled(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoriesServicesService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriesServicesServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoriesServicesService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriesServicesServiceServer).Disable(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoriesServicesService_ServiceDesc is the grpc.ServiceDesc for CategoriesServicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoriesServicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.CategoriesServicesService",
	HandlerType: (*CategoriesServicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CategoriesServicesService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CategoriesServicesService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _CategoriesServicesService_FindAll_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _CategoriesServicesService_FindOne_Handler,
		},
		{
			MethodName: "Enabled",
			Handler:    _CategoriesServicesService_Enabled_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _CategoriesServicesService_Disable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "categories_services.proto",
}
