// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: categories_services.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoriesServices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity     *Entity `protobuf:"bytes,1,opt,name=Entity,proto3" json:"Entity,omitempty"`
	IdCategory string  `protobuf:"bytes,2,opt,name=id_category,json=idCategory,proto3" json:"id_category,omitempty"`
	IdService  string  `protobuf:"bytes,3,opt,name=id_service,json=idService,proto3" json:"id_service,omitempty"`
}

func (x *CategoriesServices) Reset() {
	*x = CategoriesServices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categories_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriesServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesServices) ProtoMessage() {}

func (x *CategoriesServices) ProtoReflect() protoreflect.Message {
	mi := &file_categories_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesServices.ProtoReflect.Descriptor instead.
func (*CategoriesServices) Descriptor() ([]byte, []int) {
	return file_categories_services_proto_rawDescGZIP(), []int{0}
}

func (x *CategoriesServices) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *CategoriesServices) GetIdCategory() string {
	if x != nil {
		return x.IdCategory
	}
	return ""
}

func (x *CategoriesServices) GetIdService() string {
	if x != nil {
		return x.IdService
	}
	return ""
}

type CategoriesServicesListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  *CategoriesServices `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata *Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *CategoriesServicesListRequest) Reset() {
	*x = CategoriesServicesListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categories_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriesServicesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesServicesListRequest) ProtoMessage() {}

func (x *CategoriesServicesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_categories_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesServicesListRequest.ProtoReflect.Descriptor instead.
func (*CategoriesServicesListRequest) Descriptor() ([]byte, []int) {
	return file_categories_services_proto_rawDescGZIP(), []int{1}
}

func (x *CategoriesServicesListRequest) GetPayload() *CategoriesServices {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CategoriesServicesListRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CategoriesServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *CategoriesServices `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *CategoriesServicesResponse) Reset() {
	*x = CategoriesServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categories_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriesServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesServicesResponse) ProtoMessage() {}

func (x *CategoriesServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_categories_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesServicesResponse.ProtoReflect.Descriptor instead.
func (*CategoriesServicesResponse) Descriptor() ([]byte, []int) {
	return file_categories_services_proto_rawDescGZIP(), []int{2}
}

func (x *CategoriesServicesResponse) GetResponse() *CategoriesServices {
	if x != nil {
		return x.Response
	}
	return nil
}

type CategoriesServicesListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*CategoriesServices `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *CategoriesServicesListResponse) Reset() {
	*x = CategoriesServicesListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categories_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriesServicesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesServicesListResponse) ProtoMessage() {}

func (x *CategoriesServicesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_categories_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesServicesListResponse.ProtoReflect.Descriptor instead.
func (*CategoriesServicesListResponse) Descriptor() ([]byte, []int) {
	return file_categories_services_proto_rawDescGZIP(), []int{3}
}

func (x *CategoriesServicesListResponse) GetResponse() []*CategoriesServices {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_categories_services_proto protoreflect.FileDescriptor

var file_categories_services_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7c, 0x0a, 0x12, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x83, 0x01,
	0x0a, 0x1d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x34, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x1a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x58, 0x0a, 0x1e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x89, 0x02, 0x0a, 0x19, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x48, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x22, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x1a, 0x22, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x12, 0x25, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_categories_services_proto_rawDescOnce sync.Once
	file_categories_services_proto_rawDescData = file_categories_services_proto_rawDesc
)

func file_categories_services_proto_rawDescGZIP() []byte {
	file_categories_services_proto_rawDescOnce.Do(func() {
		file_categories_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_categories_services_proto_rawDescData)
	})
	return file_categories_services_proto_rawDescData
}

var file_categories_services_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_categories_services_proto_goTypes = []any{
	(*CategoriesServices)(nil),             // 0: domain.CategoriesServices
	(*CategoriesServicesListRequest)(nil),  // 1: domain.CategoriesServicesListRequest
	(*CategoriesServicesResponse)(nil),     // 2: domain.CategoriesServicesResponse
	(*CategoriesServicesListResponse)(nil), // 3: domain.CategoriesServicesListResponse
	(*Entity)(nil),                         // 4: domain.Entity
	(*Metadata)(nil),                       // 5: domain.Metadata
}
var file_categories_services_proto_depIdxs = []int32{
	4, // 0: domain.CategoriesServices.Entity:type_name -> domain.Entity
	0, // 1: domain.CategoriesServicesListRequest.payload:type_name -> domain.CategoriesServices
	5, // 2: domain.CategoriesServicesListRequest.metadata:type_name -> domain.Metadata
	0, // 3: domain.CategoriesServicesResponse.response:type_name -> domain.CategoriesServices
	0, // 4: domain.CategoriesServicesListResponse.response:type_name -> domain.CategoriesServices
	0, // 5: domain.CategoriesServicesService.Create:input_type -> domain.CategoriesServices
	0, // 6: domain.CategoriesServicesService.Update:input_type -> domain.CategoriesServices
	1, // 7: domain.CategoriesServicesService.FindAll:input_type -> domain.CategoriesServicesListRequest
	2, // 8: domain.CategoriesServicesService.Create:output_type -> domain.CategoriesServicesResponse
	2, // 9: domain.CategoriesServicesService.Update:output_type -> domain.CategoriesServicesResponse
	3, // 10: domain.CategoriesServicesService.FindAll:output_type -> domain.CategoriesServicesListResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_categories_services_proto_init() }
func file_categories_services_proto_init() {
	if File_categories_services_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_categories_services_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CategoriesServices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categories_services_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CategoriesServicesListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categories_services_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CategoriesServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categories_services_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CategoriesServicesListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_categories_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_categories_services_proto_goTypes,
		DependencyIndexes: file_categories_services_proto_depIdxs,
		MessageInfos:      file_categories_services_proto_msgTypes,
	}.Build()
	File_categories_services_proto = out.File
	file_categories_services_proto_rawDesc = nil
	file_categories_services_proto_goTypes = nil
	file_categories_services_proto_depIdxs = nil
}
