// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: context_domain_transaction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContextDomainTransactionService_Create_FullMethodName  = "/domain.ContextDomainTransactionService/Create"
	ContextDomainTransactionService_Update_FullMethodName  = "/domain.ContextDomainTransactionService/Update"
	ContextDomainTransactionService_FindAll_FullMethodName = "/domain.ContextDomainTransactionService/FindAll"
	ContextDomainTransactionService_FindOne_FullMethodName = "/domain.ContextDomainTransactionService/FindOne"
	ContextDomainTransactionService_Enabled_FullMethodName = "/domain.ContextDomainTransactionService/Enabled"
	ContextDomainTransactionService_Disable_FullMethodName = "/domain.ContextDomainTransactionService/Disable"
)

// ContextDomainTransactionServiceClient is the client API for ContextDomainTransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextDomainTransactionServiceClient interface {
	Create(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error)
	Update(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error)
	FindAll(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionListResponse, error)
	FindOne(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error)
	Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error)
	Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error)
}

type contextDomainTransactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContextDomainTransactionServiceClient(cc grpc.ClientConnInterface) ContextDomainTransactionServiceClient {
	return &contextDomainTransactionServiceClient{cc}
}

func (c *contextDomainTransactionServiceClient) Create(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextDomainTransactionResponse)
	err := c.cc.Invoke(ctx, ContextDomainTransactionService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextDomainTransactionServiceClient) Update(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextDomainTransactionResponse)
	err := c.cc.Invoke(ctx, ContextDomainTransactionService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextDomainTransactionServiceClient) FindAll(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextDomainTransactionListResponse)
	err := c.cc.Invoke(ctx, ContextDomainTransactionService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextDomainTransactionServiceClient) FindOne(ctx context.Context, in *ContextDomainTransactionRequest, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextDomainTransactionResponse)
	err := c.cc.Invoke(ctx, ContextDomainTransactionService_FindOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextDomainTransactionServiceClient) Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextDomainTransactionResponse)
	err := c.cc.Invoke(ctx, ContextDomainTransactionService_Enabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextDomainTransactionServiceClient) Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*ContextDomainTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextDomainTransactionResponse)
	err := c.cc.Invoke(ctx, ContextDomainTransactionService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextDomainTransactionServiceServer is the server API for ContextDomainTransactionService service.
// All implementations must embed UnimplementedContextDomainTransactionServiceServer
// for forward compatibility.
type ContextDomainTransactionServiceServer interface {
	Create(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionResponse, error)
	Update(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionResponse, error)
	FindAll(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionListResponse, error)
	FindOne(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionResponse, error)
	Enabled(context.Context, *Entity) (*ContextDomainTransactionResponse, error)
	Disable(context.Context, *Entity) (*ContextDomainTransactionResponse, error)
	mustEmbedUnimplementedContextDomainTransactionServiceServer()
}

// UnimplementedContextDomainTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContextDomainTransactionServiceServer struct{}

func (UnimplementedContextDomainTransactionServiceServer) Create(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedContextDomainTransactionServiceServer) Update(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedContextDomainTransactionServiceServer) FindAll(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedContextDomainTransactionServiceServer) FindOne(context.Context, *ContextDomainTransactionRequest) (*ContextDomainTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedContextDomainTransactionServiceServer) Enabled(context.Context, *Entity) (*ContextDomainTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enabled not implemented")
}
func (UnimplementedContextDomainTransactionServiceServer) Disable(context.Context, *Entity) (*ContextDomainTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedContextDomainTransactionServiceServer) mustEmbedUnimplementedContextDomainTransactionServiceServer() {
}
func (UnimplementedContextDomainTransactionServiceServer) testEmbeddedByValue() {}

// UnsafeContextDomainTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextDomainTransactionServiceServer will
// result in compilation errors.
type UnsafeContextDomainTransactionServiceServer interface {
	mustEmbedUnimplementedContextDomainTransactionServiceServer()
}

func RegisterContextDomainTransactionServiceServer(s grpc.ServiceRegistrar, srv ContextDomainTransactionServiceServer) {
	// If the following call pancis, it indicates UnimplementedContextDomainTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContextDomainTransactionService_ServiceDesc, srv)
}

func _ContextDomainTransactionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextDomainTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextDomainTransactionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextDomainTransactionService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextDomainTransactionServiceServer).Create(ctx, req.(*ContextDomainTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextDomainTransactionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextDomainTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextDomainTransactionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextDomainTransactionService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextDomainTransactionServiceServer).Update(ctx, req.(*ContextDomainTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextDomainTransactionService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextDomainTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextDomainTransactionServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextDomainTransactionService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextDomainTransactionServiceServer).FindAll(ctx, req.(*ContextDomainTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextDomainTransactionService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextDomainTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextDomainTransactionServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextDomainTransactionService_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextDomainTransactionServiceServer).FindOne(ctx, req.(*ContextDomainTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextDomainTransactionService_Enabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextDomainTransactionServiceServer).Enabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextDomainTransactionService_Enabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextDomainTransactionServiceServer).Enabled(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextDomainTransactionService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextDomainTransactionServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextDomainTransactionService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextDomainTransactionServiceServer).Disable(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextDomainTransactionService_ServiceDesc is the grpc.ServiceDesc for ContextDomainTransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextDomainTransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.ContextDomainTransactionService",
	HandlerType: (*ContextDomainTransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ContextDomainTransactionService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ContextDomainTransactionService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _ContextDomainTransactionService_FindAll_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _ContextDomainTransactionService_FindOne_Handler,
		},
		{
			MethodName: "Enabled",
			Handler:    _ContextDomainTransactionService_Enabled_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _ContextDomainTransactionService_Disable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "context_domain_transaction.proto",
}
