// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: partner_addresses.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartnerAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity    *Entity `protobuf:"bytes,1,opt,name=Entity,proto3" json:"Entity,omitempty"`
	IdPartner string  `protobuf:"bytes,2,opt,name=id_partner,json=idPartner,proto3" json:"id_partner,omitempty"`
	IdAddress string  `protobuf:"bytes,3,opt,name=id_address,json=idAddress,proto3" json:"id_address,omitempty"`
}

func (x *PartnerAddress) Reset() {
	*x = PartnerAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_addresses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerAddress) ProtoMessage() {}

func (x *PartnerAddress) ProtoReflect() protoreflect.Message {
	mi := &file_partner_addresses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerAddress.ProtoReflect.Descriptor instead.
func (*PartnerAddress) Descriptor() ([]byte, []int) {
	return file_partner_addresses_proto_rawDescGZIP(), []int{0}
}

func (x *PartnerAddress) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *PartnerAddress) GetIdPartner() string {
	if x != nil {
		return x.IdPartner
	}
	return ""
}

func (x *PartnerAddress) GetIdAddress() string {
	if x != nil {
		return x.IdAddress
	}
	return ""
}

type PartnerAddressListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  *PartnerAddress `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata *Metadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *PartnerAddressListRequest) Reset() {
	*x = PartnerAddressListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_addresses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerAddressListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerAddressListRequest) ProtoMessage() {}

func (x *PartnerAddressListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_addresses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerAddressListRequest.ProtoReflect.Descriptor instead.
func (*PartnerAddressListRequest) Descriptor() ([]byte, []int) {
	return file_partner_addresses_proto_rawDescGZIP(), []int{1}
}

func (x *PartnerAddressListRequest) GetPayload() *PartnerAddress {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PartnerAddressListRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PartnerAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *PartnerAddress `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PartnerAddressResponse) Reset() {
	*x = PartnerAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_addresses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerAddressResponse) ProtoMessage() {}

func (x *PartnerAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_addresses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerAddressResponse.ProtoReflect.Descriptor instead.
func (*PartnerAddressResponse) Descriptor() ([]byte, []int) {
	return file_partner_addresses_proto_rawDescGZIP(), []int{2}
}

func (x *PartnerAddressResponse) GetResponse() *PartnerAddress {
	if x != nil {
		return x.Response
	}
	return nil
}

type PartnerAddressListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*PartnerAddress `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *PartnerAddressListResponse) Reset() {
	*x = PartnerAddressListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_addresses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerAddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerAddressListResponse) ProtoMessage() {}

func (x *PartnerAddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_addresses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerAddressListResponse.ProtoReflect.Descriptor instead.
func (*PartnerAddressListResponse) Descriptor() ([]byte, []int) {
	return file_partner_addresses_proto_rawDescGZIP(), []int{3}
}

func (x *PartnerAddressListResponse) GetResponse() []*PartnerAddress {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_partner_addresses_proto protoreflect.FileDescriptor

var file_partner_addresses_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a,
	0x0e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x26, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x7b, 0x0a, 0x19, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4c, 0x0a, 0x16, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x50, 0x0a, 0x1a, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xed, 0x01, 0x0a, 0x15, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x1e,
	0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x1a, 0x1e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x21, 0x2e, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_partner_addresses_proto_rawDescOnce sync.Once
	file_partner_addresses_proto_rawDescData = file_partner_addresses_proto_rawDesc
)

func file_partner_addresses_proto_rawDescGZIP() []byte {
	file_partner_addresses_proto_rawDescOnce.Do(func() {
		file_partner_addresses_proto_rawDescData = protoimpl.X.CompressGZIP(file_partner_addresses_proto_rawDescData)
	})
	return file_partner_addresses_proto_rawDescData
}

var file_partner_addresses_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_partner_addresses_proto_goTypes = []any{
	(*PartnerAddress)(nil),             // 0: domain.PartnerAddress
	(*PartnerAddressListRequest)(nil),  // 1: domain.PartnerAddressListRequest
	(*PartnerAddressResponse)(nil),     // 2: domain.PartnerAddressResponse
	(*PartnerAddressListResponse)(nil), // 3: domain.PartnerAddressListResponse
	(*Entity)(nil),                     // 4: domain.Entity
	(*Metadata)(nil),                   // 5: domain.Metadata
}
var file_partner_addresses_proto_depIdxs = []int32{
	4, // 0: domain.PartnerAddress.Entity:type_name -> domain.Entity
	0, // 1: domain.PartnerAddressListRequest.payload:type_name -> domain.PartnerAddress
	5, // 2: domain.PartnerAddressListRequest.metadata:type_name -> domain.Metadata
	0, // 3: domain.PartnerAddressResponse.response:type_name -> domain.PartnerAddress
	0, // 4: domain.PartnerAddressListResponse.response:type_name -> domain.PartnerAddress
	0, // 5: domain.PartnerAddressService.Create:input_type -> domain.PartnerAddress
	0, // 6: domain.PartnerAddressService.Update:input_type -> domain.PartnerAddress
	1, // 7: domain.PartnerAddressService.FindAll:input_type -> domain.PartnerAddressListRequest
	2, // 8: domain.PartnerAddressService.Create:output_type -> domain.PartnerAddressResponse
	2, // 9: domain.PartnerAddressService.Update:output_type -> domain.PartnerAddressResponse
	3, // 10: domain.PartnerAddressService.FindAll:output_type -> domain.PartnerAddressListResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_partner_addresses_proto_init() }
func file_partner_addresses_proto_init() {
	if File_partner_addresses_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_partner_addresses_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_addresses_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerAddressListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_addresses_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_addresses_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerAddressListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_partner_addresses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_partner_addresses_proto_goTypes,
		DependencyIndexes: file_partner_addresses_proto_depIdxs,
		MessageInfos:      file_partner_addresses_proto_msgTypes,
	}.Build()
	File_partner_addresses_proto = out.File
	file_partner_addresses_proto_rawDesc = nil
	file_partner_addresses_proto_goTypes = nil
	file_partner_addresses_proto_depIdxs = nil
}
