// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: partners_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartnersServicesService_Create_FullMethodName  = "/domain.PartnersServicesService/Create"
	PartnersServicesService_Update_FullMethodName  = "/domain.PartnersServicesService/Update"
	PartnersServicesService_FindAll_FullMethodName = "/domain.PartnersServicesService/FindAll"
)

// PartnersServicesServiceClient is the client API for PartnersServicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartnersServicesServiceClient interface {
	Create(ctx context.Context, in *PartnersServices, opts ...grpc.CallOption) (*PartnersServicesResponse, error)
	Update(ctx context.Context, in *PartnersServices, opts ...grpc.CallOption) (*PartnersServicesResponse, error)
	FindAll(ctx context.Context, in *PartnersServicesListRequest, opts ...grpc.CallOption) (*PartnersServicesListResponse, error)
}

type partnersServicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnersServicesServiceClient(cc grpc.ClientConnInterface) PartnersServicesServiceClient {
	return &partnersServicesServiceClient{cc}
}

func (c *partnersServicesServiceClient) Create(ctx context.Context, in *PartnersServices, opts ...grpc.CallOption) (*PartnersServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnersServicesResponse)
	err := c.cc.Invoke(ctx, PartnersServicesService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnersServicesServiceClient) Update(ctx context.Context, in *PartnersServices, opts ...grpc.CallOption) (*PartnersServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnersServicesResponse)
	err := c.cc.Invoke(ctx, PartnersServicesService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnersServicesServiceClient) FindAll(ctx context.Context, in *PartnersServicesListRequest, opts ...grpc.CallOption) (*PartnersServicesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnersServicesListResponse)
	err := c.cc.Invoke(ctx, PartnersServicesService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnersServicesServiceServer is the server API for PartnersServicesService service.
// All implementations must embed UnimplementedPartnersServicesServiceServer
// for forward compatibility.
type PartnersServicesServiceServer interface {
	Create(context.Context, *PartnersServices) (*PartnersServicesResponse, error)
	Update(context.Context, *PartnersServices) (*PartnersServicesResponse, error)
	FindAll(context.Context, *PartnersServicesListRequest) (*PartnersServicesListResponse, error)
	mustEmbedUnimplementedPartnersServicesServiceServer()
}

// UnimplementedPartnersServicesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartnersServicesServiceServer struct{}

func (UnimplementedPartnersServicesServiceServer) Create(context.Context, *PartnersServices) (*PartnersServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPartnersServicesServiceServer) Update(context.Context, *PartnersServices) (*PartnersServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPartnersServicesServiceServer) FindAll(context.Context, *PartnersServicesListRequest) (*PartnersServicesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedPartnersServicesServiceServer) mustEmbedUnimplementedPartnersServicesServiceServer() {
}
func (UnimplementedPartnersServicesServiceServer) testEmbeddedByValue() {}

// UnsafePartnersServicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartnersServicesServiceServer will
// result in compilation errors.
type UnsafePartnersServicesServiceServer interface {
	mustEmbedUnimplementedPartnersServicesServiceServer()
}

func RegisterPartnersServicesServiceServer(s grpc.ServiceRegistrar, srv PartnersServicesServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartnersServicesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartnersServicesService_ServiceDesc, srv)
}

func _PartnersServicesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnersServices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnersServicesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnersServicesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnersServicesServiceServer).Create(ctx, req.(*PartnersServices))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnersServicesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnersServices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnersServicesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnersServicesService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnersServicesServiceServer).Update(ctx, req.(*PartnersServices))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnersServicesService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnersServicesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnersServicesServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnersServicesService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnersServicesServiceServer).FindAll(ctx, req.(*PartnersServicesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartnersServicesService_ServiceDesc is the grpc.ServiceDesc for PartnersServicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartnersServicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.PartnersServicesService",
	HandlerType: (*PartnersServicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PartnersServicesService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PartnersServicesService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _PartnersServicesService_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partners_service.proto",
}
