// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: partner_addresses.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartnerAddressService_Create_FullMethodName  = "/domain.PartnerAddressService/Create"
	PartnerAddressService_Update_FullMethodName  = "/domain.PartnerAddressService/Update"
	PartnerAddressService_FindAll_FullMethodName = "/domain.PartnerAddressService/FindAll"
	PartnerAddressService_FindOne_FullMethodName = "/domain.PartnerAddressService/FindOne"
	PartnerAddressService_Enabled_FullMethodName = "/domain.PartnerAddressService/Enabled"
	PartnerAddressService_Disable_FullMethodName = "/domain.PartnerAddressService/Disable"
)

// PartnerAddressServiceClient is the client API for PartnerAddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartnerAddressServiceClient interface {
	Create(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressResponse, error)
	Update(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressResponse, error)
	FindAll(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressListResponse, error)
	FindOne(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressResponse, error)
	Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerAddressResponse, error)
	Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerAddressResponse, error)
}

type partnerAddressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnerAddressServiceClient(cc grpc.ClientConnInterface) PartnerAddressServiceClient {
	return &partnerAddressServiceClient{cc}
}

func (c *partnerAddressServiceClient) Create(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerAddressResponse)
	err := c.cc.Invoke(ctx, PartnerAddressService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAddressServiceClient) Update(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerAddressResponse)
	err := c.cc.Invoke(ctx, PartnerAddressService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAddressServiceClient) FindAll(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerAddressListResponse)
	err := c.cc.Invoke(ctx, PartnerAddressService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAddressServiceClient) FindOne(ctx context.Context, in *PartnerAddressRequest, opts ...grpc.CallOption) (*PartnerAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerAddressResponse)
	err := c.cc.Invoke(ctx, PartnerAddressService_FindOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAddressServiceClient) Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerAddressResponse)
	err := c.cc.Invoke(ctx, PartnerAddressService_Enabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerAddressServiceClient) Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerAddressResponse)
	err := c.cc.Invoke(ctx, PartnerAddressService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerAddressServiceServer is the server API for PartnerAddressService service.
// All implementations must embed UnimplementedPartnerAddressServiceServer
// for forward compatibility.
type PartnerAddressServiceServer interface {
	Create(context.Context, *PartnerAddressRequest) (*PartnerAddressResponse, error)
	Update(context.Context, *PartnerAddressRequest) (*PartnerAddressResponse, error)
	FindAll(context.Context, *PartnerAddressRequest) (*PartnerAddressListResponse, error)
	FindOne(context.Context, *PartnerAddressRequest) (*PartnerAddressResponse, error)
	Enabled(context.Context, *Entity) (*PartnerAddressResponse, error)
	Disable(context.Context, *Entity) (*PartnerAddressResponse, error)
	mustEmbedUnimplementedPartnerAddressServiceServer()
}

// UnimplementedPartnerAddressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartnerAddressServiceServer struct{}

func (UnimplementedPartnerAddressServiceServer) Create(context.Context, *PartnerAddressRequest) (*PartnerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPartnerAddressServiceServer) Update(context.Context, *PartnerAddressRequest) (*PartnerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPartnerAddressServiceServer) FindAll(context.Context, *PartnerAddressRequest) (*PartnerAddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedPartnerAddressServiceServer) FindOne(context.Context, *PartnerAddressRequest) (*PartnerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedPartnerAddressServiceServer) Enabled(context.Context, *Entity) (*PartnerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enabled not implemented")
}
func (UnimplementedPartnerAddressServiceServer) Disable(context.Context, *Entity) (*PartnerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedPartnerAddressServiceServer) mustEmbedUnimplementedPartnerAddressServiceServer() {}
func (UnimplementedPartnerAddressServiceServer) testEmbeddedByValue()                               {}

// UnsafePartnerAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartnerAddressServiceServer will
// result in compilation errors.
type UnsafePartnerAddressServiceServer interface {
	mustEmbedUnimplementedPartnerAddressServiceServer()
}

func RegisterPartnerAddressServiceServer(s grpc.ServiceRegistrar, srv PartnerAddressServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartnerAddressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartnerAddressService_ServiceDesc, srv)
}

func _PartnerAddressService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAddressServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerAddressService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAddressServiceServer).Create(ctx, req.(*PartnerAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAddressService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAddressServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerAddressService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAddressServiceServer).Update(ctx, req.(*PartnerAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAddressService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAddressServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerAddressService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAddressServiceServer).FindAll(ctx, req.(*PartnerAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAddressService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAddressServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerAddressService_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAddressServiceServer).FindOne(ctx, req.(*PartnerAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAddressService_Enabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAddressServiceServer).Enabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerAddressService_Enabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAddressServiceServer).Enabled(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerAddressService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerAddressServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerAddressService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerAddressServiceServer).Disable(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

// PartnerAddressService_ServiceDesc is the grpc.ServiceDesc for PartnerAddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartnerAddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.PartnerAddressService",
	HandlerType: (*PartnerAddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PartnerAddressService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PartnerAddressService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _PartnerAddressService_FindAll_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _PartnerAddressService_FindOne_Handler,
		},
		{
			MethodName: "Enabled",
			Handler:    _PartnerAddressService_Enabled_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _PartnerAddressService_Disable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partner_addresses.proto",
}
