// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: partners_users.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartnerUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity            *Entity `protobuf:"bytes,1,opt,name=Entity,proto3" json:"Entity,omitempty"`
	IdPartner         string  `protobuf:"bytes,2,opt,name=id_partner,json=idPartner,proto3" json:"id_partner,omitempty"`
	Name              int32   `protobuf:"varint,3,opt,name=name,proto3" json:"name,omitempty"`
	Username          string  `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	IdCognito         string  `protobuf:"bytes,5,opt,name=id_cognito,json=idCognito,proto3" json:"id_cognito,omitempty"`
	IdRoleApplication string  `protobuf:"bytes,6,opt,name=id_role_application,json=idRoleApplication,proto3" json:"id_role_application,omitempty"`
}

func (x *PartnerUser) Reset() {
	*x = PartnerUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_users_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerUser) ProtoMessage() {}

func (x *PartnerUser) ProtoReflect() protoreflect.Message {
	mi := &file_partners_users_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerUser.ProtoReflect.Descriptor instead.
func (*PartnerUser) Descriptor() ([]byte, []int) {
	return file_partners_users_proto_rawDescGZIP(), []int{0}
}

func (x *PartnerUser) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *PartnerUser) GetIdPartner() string {
	if x != nil {
		return x.IdPartner
	}
	return ""
}

func (x *PartnerUser) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *PartnerUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PartnerUser) GetIdCognito() string {
	if x != nil {
		return x.IdCognito
	}
	return ""
}

func (x *PartnerUser) GetIdRoleApplication() string {
	if x != nil {
		return x.IdRoleApplication
	}
	return ""
}

type PartnerUserListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  *PartnerUser `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata *Metadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *PartnerUserListRequest) Reset() {
	*x = PartnerUserListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_users_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerUserListRequest) ProtoMessage() {}

func (x *PartnerUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partners_users_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerUserListRequest.ProtoReflect.Descriptor instead.
func (*PartnerUserListRequest) Descriptor() ([]byte, []int) {
	return file_partners_users_proto_rawDescGZIP(), []int{1}
}

func (x *PartnerUserListRequest) GetPayload() *PartnerUser {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PartnerUserListRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PartnerUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *PartnerUser `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PartnerUserResponse) Reset() {
	*x = PartnerUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_users_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerUserResponse) ProtoMessage() {}

func (x *PartnerUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partners_users_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerUserResponse.ProtoReflect.Descriptor instead.
func (*PartnerUserResponse) Descriptor() ([]byte, []int) {
	return file_partners_users_proto_rawDescGZIP(), []int{2}
}

func (x *PartnerUserResponse) GetResponse() *PartnerUser {
	if x != nil {
		return x.Response
	}
	return nil
}

type PartnerUserListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*PartnerUser `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *PartnerUserListResponse) Reset() {
	*x = PartnerUserListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_users_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerUserListResponse) ProtoMessage() {}

func (x *PartnerUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partners_users_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerUserListResponse.ProtoReflect.Descriptor instead.
func (*PartnerUserListResponse) Descriptor() ([]byte, []int) {
	return file_partners_users_proto_rawDescGZIP(), []int{3}
}

func (x *PartnerUserListResponse) GetResponse() []*PartnerUser {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_partners_users_proto protoreflect.FileDescriptor

var file_partners_users_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x0a,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x01, 0x0a, 0x0b, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x43, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x6f,
	0x12, 0x2e, 0x0a, 0x13, 0x69, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x69,
	0x64, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x75, 0x0a, 0x16, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x13, 0x50, 0x61, 0x72, 0x74, 0x6e,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x4a, 0x0a, 0x17, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd8, 0x01, 0x0a, 0x12,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x1a, 0x1b, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1b, 0x2e,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_partners_users_proto_rawDescOnce sync.Once
	file_partners_users_proto_rawDescData = file_partners_users_proto_rawDesc
)

func file_partners_users_proto_rawDescGZIP() []byte {
	file_partners_users_proto_rawDescOnce.Do(func() {
		file_partners_users_proto_rawDescData = protoimpl.X.CompressGZIP(file_partners_users_proto_rawDescData)
	})
	return file_partners_users_proto_rawDescData
}

var file_partners_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_partners_users_proto_goTypes = []any{
	(*PartnerUser)(nil),             // 0: domain.PartnerUser
	(*PartnerUserListRequest)(nil),  // 1: domain.PartnerUserListRequest
	(*PartnerUserResponse)(nil),     // 2: domain.PartnerUserResponse
	(*PartnerUserListResponse)(nil), // 3: domain.PartnerUserListResponse
	(*Entity)(nil),                  // 4: domain.Entity
	(*Metadata)(nil),                // 5: domain.Metadata
}
var file_partners_users_proto_depIdxs = []int32{
	4, // 0: domain.PartnerUser.Entity:type_name -> domain.Entity
	0, // 1: domain.PartnerUserListRequest.payload:type_name -> domain.PartnerUser
	5, // 2: domain.PartnerUserListRequest.metadata:type_name -> domain.Metadata
	0, // 3: domain.PartnerUserResponse.response:type_name -> domain.PartnerUser
	0, // 4: domain.PartnerUserListResponse.response:type_name -> domain.PartnerUser
	0, // 5: domain.PartnerUserService.Create:input_type -> domain.PartnerUser
	0, // 6: domain.PartnerUserService.Update:input_type -> domain.PartnerUser
	1, // 7: domain.PartnerUserService.FindAll:input_type -> domain.PartnerUserListRequest
	2, // 8: domain.PartnerUserService.Create:output_type -> domain.PartnerUserResponse
	2, // 9: domain.PartnerUserService.Update:output_type -> domain.PartnerUserResponse
	3, // 10: domain.PartnerUserService.FindAll:output_type -> domain.PartnerUserListResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_partners_users_proto_init() }
func file_partners_users_proto_init() {
	if File_partners_users_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_partners_users_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_users_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerUserListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_users_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_users_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PartnerUserListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_partners_users_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_partners_users_proto_goTypes,
		DependencyIndexes: file_partners_users_proto_depIdxs,
		MessageInfos:      file_partners_users_proto_msgTypes,
	}.Build()
	File_partners_users_proto = out.File
	file_partners_users_proto_rawDesc = nil
	file_partners_users_proto_goTypes = nil
	file_partners_users_proto_depIdxs = nil
}
