// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: partners_contacts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartnerContactService_Create_FullMethodName  = "/domain.PartnerContactService/Create"
	PartnerContactService_Update_FullMethodName  = "/domain.PartnerContactService/Update"
	PartnerContactService_FindAll_FullMethodName = "/domain.PartnerContactService/FindAll"
)

// PartnerContactServiceClient is the client API for PartnerContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartnerContactServiceClient interface {
	Create(ctx context.Context, in *PartnerContact, opts ...grpc.CallOption) (*PartnerContactResponse, error)
	Update(ctx context.Context, in *PartnerContact, opts ...grpc.CallOption) (*PartnerContactResponse, error)
	FindAll(ctx context.Context, in *PartnerContactListRequest, opts ...grpc.CallOption) (*PartnerContactListResponse, error)
}

type partnerContactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnerContactServiceClient(cc grpc.ClientConnInterface) PartnerContactServiceClient {
	return &partnerContactServiceClient{cc}
}

func (c *partnerContactServiceClient) Create(ctx context.Context, in *PartnerContact, opts ...grpc.CallOption) (*PartnerContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerContactResponse)
	err := c.cc.Invoke(ctx, PartnerContactService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerContactServiceClient) Update(ctx context.Context, in *PartnerContact, opts ...grpc.CallOption) (*PartnerContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerContactResponse)
	err := c.cc.Invoke(ctx, PartnerContactService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerContactServiceClient) FindAll(ctx context.Context, in *PartnerContactListRequest, opts ...grpc.CallOption) (*PartnerContactListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerContactListResponse)
	err := c.cc.Invoke(ctx, PartnerContactService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerContactServiceServer is the server API for PartnerContactService service.
// All implementations must embed UnimplementedPartnerContactServiceServer
// for forward compatibility.
type PartnerContactServiceServer interface {
	Create(context.Context, *PartnerContact) (*PartnerContactResponse, error)
	Update(context.Context, *PartnerContact) (*PartnerContactResponse, error)
	FindAll(context.Context, *PartnerContactListRequest) (*PartnerContactListResponse, error)
	mustEmbedUnimplementedPartnerContactServiceServer()
}

// UnimplementedPartnerContactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartnerContactServiceServer struct{}

func (UnimplementedPartnerContactServiceServer) Create(context.Context, *PartnerContact) (*PartnerContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPartnerContactServiceServer) Update(context.Context, *PartnerContact) (*PartnerContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPartnerContactServiceServer) FindAll(context.Context, *PartnerContactListRequest) (*PartnerContactListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedPartnerContactServiceServer) mustEmbedUnimplementedPartnerContactServiceServer() {}
func (UnimplementedPartnerContactServiceServer) testEmbeddedByValue()                               {}

// UnsafePartnerContactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartnerContactServiceServer will
// result in compilation errors.
type UnsafePartnerContactServiceServer interface {
	mustEmbedUnimplementedPartnerContactServiceServer()
}

func RegisterPartnerContactServiceServer(s grpc.ServiceRegistrar, srv PartnerContactServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartnerContactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartnerContactService_ServiceDesc, srv)
}

func _PartnerContactService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerContact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerContactServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerContactService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerContactServiceServer).Create(ctx, req.(*PartnerContact))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerContactService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerContact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerContactServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerContactService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerContactServiceServer).Update(ctx, req.(*PartnerContact))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerContactService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerContactListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerContactServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerContactService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerContactServiceServer).FindAll(ctx, req.(*PartnerContactListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartnerContactService_ServiceDesc is the grpc.ServiceDesc for PartnerContactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartnerContactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.PartnerContactService",
	HandlerType: (*PartnerContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PartnerContactService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PartnerContactService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _PartnerContactService_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partners_contacts.proto",
}
