// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: partners_users.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartnerUserService_Create_FullMethodName  = "/domain.PartnerUserService/Create"
	PartnerUserService_Update_FullMethodName  = "/domain.PartnerUserService/Update"
	PartnerUserService_FindAll_FullMethodName = "/domain.PartnerUserService/FindAll"
)

// PartnerUserServiceClient is the client API for PartnerUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartnerUserServiceClient interface {
	Create(ctx context.Context, in *PartnerUser, opts ...grpc.CallOption) (*PartnerUserResponse, error)
	Update(ctx context.Context, in *PartnerUser, opts ...grpc.CallOption) (*PartnerUserResponse, error)
	FindAll(ctx context.Context, in *PartnerUserListRequest, opts ...grpc.CallOption) (*PartnerUserListResponse, error)
}

type partnerUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnerUserServiceClient(cc grpc.ClientConnInterface) PartnerUserServiceClient {
	return &partnerUserServiceClient{cc}
}

func (c *partnerUserServiceClient) Create(ctx context.Context, in *PartnerUser, opts ...grpc.CallOption) (*PartnerUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerUserResponse)
	err := c.cc.Invoke(ctx, PartnerUserService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerUserServiceClient) Update(ctx context.Context, in *PartnerUser, opts ...grpc.CallOption) (*PartnerUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerUserResponse)
	err := c.cc.Invoke(ctx, PartnerUserService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerUserServiceClient) FindAll(ctx context.Context, in *PartnerUserListRequest, opts ...grpc.CallOption) (*PartnerUserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerUserListResponse)
	err := c.cc.Invoke(ctx, PartnerUserService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerUserServiceServer is the server API for PartnerUserService service.
// All implementations must embed UnimplementedPartnerUserServiceServer
// for forward compatibility.
type PartnerUserServiceServer interface {
	Create(context.Context, *PartnerUser) (*PartnerUserResponse, error)
	Update(context.Context, *PartnerUser) (*PartnerUserResponse, error)
	FindAll(context.Context, *PartnerUserListRequest) (*PartnerUserListResponse, error)
	mustEmbedUnimplementedPartnerUserServiceServer()
}

// UnimplementedPartnerUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartnerUserServiceServer struct{}

func (UnimplementedPartnerUserServiceServer) Create(context.Context, *PartnerUser) (*PartnerUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPartnerUserServiceServer) Update(context.Context, *PartnerUser) (*PartnerUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPartnerUserServiceServer) FindAll(context.Context, *PartnerUserListRequest) (*PartnerUserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedPartnerUserServiceServer) mustEmbedUnimplementedPartnerUserServiceServer() {}
func (UnimplementedPartnerUserServiceServer) testEmbeddedByValue()                            {}

// UnsafePartnerUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartnerUserServiceServer will
// result in compilation errors.
type UnsafePartnerUserServiceServer interface {
	mustEmbedUnimplementedPartnerUserServiceServer()
}

func RegisterPartnerUserServiceServer(s grpc.ServiceRegistrar, srv PartnerUserServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartnerUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartnerUserService_ServiceDesc, srv)
}

func _PartnerUserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerUserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerUserService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerUserServiceServer).Create(ctx, req.(*PartnerUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerUserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerUserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerUserService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerUserServiceServer).Update(ctx, req.(*PartnerUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerUserService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerUserServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerUserService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerUserServiceServer).FindAll(ctx, req.(*PartnerUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartnerUserService_ServiceDesc is the grpc.ServiceDesc for PartnerUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartnerUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.PartnerUserService",
	HandlerType: (*PartnerUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PartnerUserService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PartnerUserService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _PartnerUserService_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partners_users.proto",
}
