// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: partners.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartnerService_Create_FullMethodName  = "/domain.PartnerService/Create"
	PartnerService_Update_FullMethodName  = "/domain.PartnerService/Update"
	PartnerService_FindAll_FullMethodName = "/domain.PartnerService/FindAll"
	PartnerService_FindOne_FullMethodName = "/domain.PartnerService/FindOne"
	PartnerService_Enabled_FullMethodName = "/domain.PartnerService/Enabled"
	PartnerService_Disable_FullMethodName = "/domain.PartnerService/Disable"
)

// PartnerServiceClient is the client API for PartnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartnerServiceClient interface {
	Create(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerResponse, error)
	Update(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerResponse, error)
	FindAll(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerListResponse, error)
	FindOne(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerResponse, error)
	Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerResponse, error)
	Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerResponse, error)
}

type partnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnerServiceClient(cc grpc.ClientConnInterface) PartnerServiceClient {
	return &partnerServiceClient{cc}
}

func (c *partnerServiceClient) Create(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerResponse)
	err := c.cc.Invoke(ctx, PartnerService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) Update(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerResponse)
	err := c.cc.Invoke(ctx, PartnerService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) FindAll(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerListResponse)
	err := c.cc.Invoke(ctx, PartnerService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) FindOne(ctx context.Context, in *PartnerRequest, opts ...grpc.CallOption) (*PartnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerResponse)
	err := c.cc.Invoke(ctx, PartnerService_FindOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerResponse)
	err := c.cc.Invoke(ctx, PartnerService_Enabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*PartnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartnerResponse)
	err := c.cc.Invoke(ctx, PartnerService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerServiceServer is the server API for PartnerService service.
// All implementations must embed UnimplementedPartnerServiceServer
// for forward compatibility.
type PartnerServiceServer interface {
	Create(context.Context, *PartnerRequest) (*PartnerResponse, error)
	Update(context.Context, *PartnerRequest) (*PartnerResponse, error)
	FindAll(context.Context, *PartnerRequest) (*PartnerListResponse, error)
	FindOne(context.Context, *PartnerRequest) (*PartnerResponse, error)
	Enabled(context.Context, *Entity) (*PartnerResponse, error)
	Disable(context.Context, *Entity) (*PartnerResponse, error)
	mustEmbedUnimplementedPartnerServiceServer()
}

// UnimplementedPartnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartnerServiceServer struct{}

func (UnimplementedPartnerServiceServer) Create(context.Context, *PartnerRequest) (*PartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPartnerServiceServer) Update(context.Context, *PartnerRequest) (*PartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPartnerServiceServer) FindAll(context.Context, *PartnerRequest) (*PartnerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedPartnerServiceServer) FindOne(context.Context, *PartnerRequest) (*PartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedPartnerServiceServer) Enabled(context.Context, *Entity) (*PartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enabled not implemented")
}
func (UnimplementedPartnerServiceServer) Disable(context.Context, *Entity) (*PartnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedPartnerServiceServer) mustEmbedUnimplementedPartnerServiceServer() {}
func (UnimplementedPartnerServiceServer) testEmbeddedByValue()                        {}

// UnsafePartnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartnerServiceServer will
// result in compilation errors.
type UnsafePartnerServiceServer interface {
	mustEmbedUnimplementedPartnerServiceServer()
}

func RegisterPartnerServiceServer(s grpc.ServiceRegistrar, srv PartnerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartnerService_ServiceDesc, srv)
}

func _PartnerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).Create(ctx, req.(*PartnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).Update(ctx, req.(*PartnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).FindAll(ctx, req.(*PartnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).FindOne(ctx, req.(*PartnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_Enabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).Enabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_Enabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).Enabled(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).Disable(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

// PartnerService_ServiceDesc is the grpc.ServiceDesc for PartnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.PartnerService",
	HandlerType: (*PartnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PartnerService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PartnerService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _PartnerService_FindAll_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _PartnerService_FindOne_Handler,
		},
		{
			MethodName: "Enabled",
			Handler:    _PartnerService_Enabled_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _PartnerService_Disable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partners.proto",
}
