// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: roles_polices.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolePolicyService_Create_FullMethodName  = "/domain.RolePolicyService/Create"
	RolePolicyService_Update_FullMethodName  = "/domain.RolePolicyService/Update"
	RolePolicyService_FindAll_FullMethodName = "/domain.RolePolicyService/FindAll"
	RolePolicyService_FindOne_FullMethodName = "/domain.RolePolicyService/FindOne"
	RolePolicyService_Enabled_FullMethodName = "/domain.RolePolicyService/Enabled"
	RolePolicyService_Disable_FullMethodName = "/domain.RolePolicyService/Disable"
)

// RolePolicyServiceClient is the client API for RolePolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RolePolicyServiceClient interface {
	Create(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyResponse, error)
	Update(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyResponse, error)
	FindAll(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyListResponse, error)
	FindOne(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyResponse, error)
	Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*RolePolicyResponse, error)
	Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*RolePolicyResponse, error)
}

type rolePolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolePolicyServiceClient(cc grpc.ClientConnInterface) RolePolicyServiceClient {
	return &rolePolicyServiceClient{cc}
}

func (c *rolePolicyServiceClient) Create(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePolicyResponse)
	err := c.cc.Invoke(ctx, RolePolicyService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePolicyServiceClient) Update(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePolicyResponse)
	err := c.cc.Invoke(ctx, RolePolicyService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePolicyServiceClient) FindAll(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePolicyListResponse)
	err := c.cc.Invoke(ctx, RolePolicyService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePolicyServiceClient) FindOne(ctx context.Context, in *RolePolicyRequest, opts ...grpc.CallOption) (*RolePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePolicyResponse)
	err := c.cc.Invoke(ctx, RolePolicyService_FindOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePolicyServiceClient) Enabled(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*RolePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePolicyResponse)
	err := c.cc.Invoke(ctx, RolePolicyService_Enabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePolicyServiceClient) Disable(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*RolePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePolicyResponse)
	err := c.cc.Invoke(ctx, RolePolicyService_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolePolicyServiceServer is the server API for RolePolicyService service.
// All implementations must embed UnimplementedRolePolicyServiceServer
// for forward compatibility.
type RolePolicyServiceServer interface {
	Create(context.Context, *RolePolicyRequest) (*RolePolicyResponse, error)
	Update(context.Context, *RolePolicyRequest) (*RolePolicyResponse, error)
	FindAll(context.Context, *RolePolicyRequest) (*RolePolicyListResponse, error)
	FindOne(context.Context, *RolePolicyRequest) (*RolePolicyResponse, error)
	Enabled(context.Context, *Entity) (*RolePolicyResponse, error)
	Disable(context.Context, *Entity) (*RolePolicyResponse, error)
	mustEmbedUnimplementedRolePolicyServiceServer()
}

// UnimplementedRolePolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolePolicyServiceServer struct{}

func (UnimplementedRolePolicyServiceServer) Create(context.Context, *RolePolicyRequest) (*RolePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRolePolicyServiceServer) Update(context.Context, *RolePolicyRequest) (*RolePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRolePolicyServiceServer) FindAll(context.Context, *RolePolicyRequest) (*RolePolicyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedRolePolicyServiceServer) FindOne(context.Context, *RolePolicyRequest) (*RolePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedRolePolicyServiceServer) Enabled(context.Context, *Entity) (*RolePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enabled not implemented")
}
func (UnimplementedRolePolicyServiceServer) Disable(context.Context, *Entity) (*RolePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedRolePolicyServiceServer) mustEmbedUnimplementedRolePolicyServiceServer() {}
func (UnimplementedRolePolicyServiceServer) testEmbeddedByValue()                           {}

// UnsafeRolePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolePolicyServiceServer will
// result in compilation errors.
type UnsafeRolePolicyServiceServer interface {
	mustEmbedUnimplementedRolePolicyServiceServer()
}

func RegisterRolePolicyServiceServer(s grpc.ServiceRegistrar, srv RolePolicyServiceServer) {
	// If the following call pancis, it indicates UnimplementedRolePolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolePolicyService_ServiceDesc, srv)
}

func _RolePolicyService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePolicyServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePolicyService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePolicyServiceServer).Create(ctx, req.(*RolePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePolicyService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePolicyServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePolicyService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePolicyServiceServer).Update(ctx, req.(*RolePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePolicyService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePolicyServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePolicyService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePolicyServiceServer).FindAll(ctx, req.(*RolePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePolicyService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePolicyServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePolicyService_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePolicyServiceServer).FindOne(ctx, req.(*RolePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePolicyService_Enabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePolicyServiceServer).Enabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePolicyService_Enabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePolicyServiceServer).Enabled(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePolicyService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePolicyServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePolicyService_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePolicyServiceServer).Disable(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

// RolePolicyService_ServiceDesc is the grpc.ServiceDesc for RolePolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolePolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.RolePolicyService",
	HandlerType: (*RolePolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RolePolicyService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RolePolicyService_Update_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _RolePolicyService_FindAll_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _RolePolicyService_FindOne_Handler,
		},
		{
			MethodName: "Enabled",
			Handler:    _RolePolicyService_Enabled_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _RolePolicyService_Disable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roles_polices.proto",
}
