name: Generate Protobuf

on:
  workflow_dispatch: 
  push:
    branches:
      - main
      - development
      - staging
  pull_request:
    branches:
      - main
      - development
      - staging

jobs:
  generate-protobuf:
    runs-on: ubuntu-latest

    steps:
      # Checa o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instala protoc (Protocol Buffers Compiler)
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      # Instala o plugin do Go para protobuf e gRPC
      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          
      # Adiciona o diretório Go bin ao PATH (normalmente $HOME/go/bin)
      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      # Gera os arquivos protobuf para Go
      - name: Generate protobuf
        run: |
          mkdir -p gen/pb
          protoc --go_out=gen/pb --go_opt=paths=source_relative \
                 --go-grpc_out=gen/pb --go-grpc_opt=paths=source_relative \
                 proto/*.proto

      # Verifica se houve alguma alteração nos arquivos gerados
      - name: Check for changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git checkout ${{ github.ref_name }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'guilherme.giusti04@gmail.com'
          git add .
          git commit -m "Regenerate protobuf files"
          git push origin $branch_name

